version: 2
updates:
  - package-ecosystem: "npm" # or "pip", "maven", "gradle", etc.
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"